version: "3.8"

services:
  app:
    container_name: backend
    # image: indamutsa/app-item:1.0.2
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    container_name: postgres
    image: indamutsa/db-item:1.0.1
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  angular:
    container_name: angular
    # image: indamutsa/angular-item:1.0.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: always

  adminer:
    container_name: adminer
    image: adminer:4.8.1-standalone
    ports:
      - 8099:8080
    depends_on:
      - db
    restart: always

  data-generator:
    image: indamutsa/data-generator-item:1.0.2
    # build: ./data-gen
    container_name: data-generator
    depends_on:
      - app
      - db
      - adminer
      - angular
    restart: on-failure
