# adminer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adminer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.adminer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminer.name }}
    spec:
      containers:
        - name: {{ .Values.adminer.name }}
          image: "{{ .Values.adminer.image }}"
          ports:
            - containerPort: {{ .Values.adminer.containerPort }}
