# angular-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.angular.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.angular.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.angular.name }}
    spec:
      containers:
      - name: {{ .Values.angular.name }}
        image: "{{ .Values.angular.image }}"
        ports:
        - containerPort: {{ .Values.angular.containerPort }}