# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.containerPort }}
  selector:
    app: {{ .Values.app.name }}
